
defaults:
  - loss: dice_loss.yaml
  - architectures: ['','','','']

_target_: src.models.rs_simple_model.RSSensembleModel
dir_preds_test: ${preds_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S}
lr: 0.001
use_scheduler: False