_target_: src.models.rs_simple_unet_backboned_model.RSSimpleUNETBackbonedModel
in_channels: 3
out_channels: 1
dir_preds_test: ${logs_dir}/predictions/${now:%Y-%m-%d}/${now:%H-%M-%S}
backbone_name: resnet152
classes: 2
