comet:
  _target_: pytorch_lightning.loggers.comet.CometLogger
  api_key: ${oc.env:COMET_API_KEY}
  workspace: ${oc.env:COMET_WORKSPACE} 
  project_name: "cil_road_segmentation"
  experiment_name: null