# @package _global_

defaults:
  - trainer: default_trainer.yaml
  - model: rs_simple_model.yaml
  - datamodule: rs_simple_datamodule.yaml 
  - callbacks: default_callbacks.yaml
  - logger: comet.yaml 

work_dir: /cluster/scratch/aruzzi
data_dir: ${work_dir}/data 
logs_dir: ${work_dir}/logs
ckpts_dir: ${logs_dir}/ckpts
preds_dir: ${logs_dir}/preds

debug: False # This uses pytorch-lighning fast_dev_run
print_config: True # Pretty prints configs at the start of run 
disable_warnings: False 
test: False # Set to true to run the model only on the test set, must include +model.checkpoint_path=path 
test_on_best: False # Use best checkpoint during test must have ModelCheckpoint active, if False will use the last 


hydra:
  # Output paths for hydra logs
  run:
    dir: ${logs_dir}/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${logs_dir}/multiruns/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}