# @package _global_

defaults:
  - trainer: default_trainer.yaml
  - model: rs_simple_base_model.yaml
  - datamodule: rs_simple_datamodule.yaml 
  - optimizer: adam.yaml 
  - callbacks: default_callbacks.yaml
  - logger: comet.yaml 

work_dir: ${hydra:runtime.cwd}
data_dir: ${work_dir}/data 
debug: False # This uses pytorch-lighning fast_dev_run
print_config: True # Pretty prints configs at the start of run 
disable_warnings: False 

hydra:
  # Output paths for hydra logs
  run:
    dir: logs/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: logs/multiruns/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}