_target_: src.pl_datamodules.road_segmentation_datamodule.RoadSegmentationDataModule
data_dir: ${data_dir}  # data_dir is specified in config.yaml
batch_size: 32
train_val_split: [80, 20]
num_workers: 4
pin_memory: False

defaults:
  - transforms: default_transform.yaml




