_target_: src.datamodules.rs_simple_datamodule.RSSimpleDataModule
data_dir: ${data_dir}  # data_dir is specified in config.yaml
batch_size: 8
train_val_split: [80, 20]    #train size = length_kaggle + length_google_maps
num_workers: 0
pin_memory: False

defaults:
  - transforms_train: transforms_0_418x418.yaml
  - transforms_test: transforms_0_418x418.yaml




