_target_: src.datasets.transforms.compose.Compose 
transforms: 
  - _target_: src.datasets.transforms.to_tensor.ToTensor
  - _target_: src.datasets.transforms.random_choice_compose.RandomChoiceCompose # Picks one of the following transforms at random 
    transforms: 
      - _target_: src.datasets.transforms.random_flip.RandomFlip
      - _target_: src.datasets.transforms.random_affine.RandomAffine
        degrees: [30, 30]         
      #- _target_: src.datasets.transforms.random_crop.RandomCrop # This must be fixed to return always images of size 1x400x400
      - _target_: src.datasets.transforms.distinct.Distinct # Applies only a grayscale transform on the first image
        transforms: 
          - _target_: torchvision.transforms.Grayscale
            num_output_channels: 3 
      - _target_: src.datasets.transforms.distinct.Distinct # Applies only an erasing transform on the first image 
        transforms:
          - _target_: torchvision.transforms.RandomErasing 
            p: 1.0 
      - _target_: src.datasets.transforms.identity.Identity # Do nothing, i.e. keep the original image 

        
        